### ISSUE TITLE
"Loading..." in lyrics panel

### ISSUE THREAD

**Issue by Luckz** [thiagoribeir015/spotify-control-chrome-extension#19]
It never loads.

I don't see the background page trying to make any network requests.

**Comment by FiXato** [comment]
I guess it might have something to do with the certificate that expired since the 6th of January 2020:

```
spotify-lyrics.vaslyn.epi.codes/:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
main.js:221 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by thiagoribeir015** [comment]
Fixed on the latest version.
